cmake_minimum_required(VERSION 3.15)
set(HEX_PREFIX "\; device = mm-control\n\n")
set(HEX_NAME "MMU2SR_${PROJECT_VERSION}${PROJECT_VERSION_SUFFIX_SHORT}.hex")
file(READ ${WORK_DIR}/firmware.hex HEX)
file(WRITE ${WORK_DIR}/${HEX_NAME} ${HEX_PREFIX})
file(APPEND ${WORK_DIR}/${HEX_NAME} ${HEX})
message(status "Successfully built MMU2SR_${PROJECT_VERSION}${PROJECT_VERSION_SUFFIX_SHORT}.hex!")
