cmake_minimum_required(VERSION 2.8)
set(HEX_PREFIX "\; device = mm-control\n\n")
file(READ ${WORK_DIR}/firmware.hex HEX)
file(WRITE ${WORK_DIR}/${HEX_NAME} ${HEX_PREFIX})
file(APPEND ${WORK_DIR}/${HEX_NAME} ${HEX})
message(status "Successfully built ${HEX_NAME}!")
